# Generated by Django 5.2.5 on 2025-08-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('annual', 'Annual'), ('quarter', 'Quarterly')], max_length=10)),
                ('period_end_date', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_quarter', models.IntegerField(blank=True, null=True)),
                ('metric', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, max_digits=24, null=True)),
                ('source', models.CharField(default='reported', max_length=40)),
                ('as_reported_currency', models.CharField(default='USD', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'metric'], name='fundamental_company_fdb61f_idx'), models.Index(fields=['company', 'period_type', 'period_end_date'], name='fundamental_company_08d2cd_idx')],
                'unique_together': {('company', 'period_type', 'period_end_date', 'metric')},
            },
        ),
    ]
