# Generated by Django 5.2.5 on 2025-08-25 09:53

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_industryplayer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=40)),
                ('object_id', models.IntegerField()),
                ('chunk_id', models.IntegerField(default=0)),
                ('model_name', models.CharField(max_length=64)),
                ('dim', models.IntegerField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=1024)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='research_re_object__72b300_idx')],
            },
        ),
    ]
