# Generated by Django 5.2.5 on 2025-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycatalyst',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyrelatedstock',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyrisk',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companythesis',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='industryplayer',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='industryprofile',
            name='context_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
