# Generated by Django 5.2.5 on 2025-08-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_companycatalyst_context_text_and_more'),
    ]

    operations = [
    ]
