# Generated by Django 5.2.5 on 2025-08-27 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_initial'),
        ('research', '0006_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCompanySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('score', models.FloatField(default=0.0)),
                ('details_json', models.JSONField(default=list)),
                ('top_news_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'window_end'], name='research_an_company_4ff548_idx'), models.Index(fields=['window_start', 'window_end'], name='research_an_window__922e7d_idx')],
                'unique_together': {('company', 'window_start', 'window_end')},
            },
        ),
    ]
