# Generated by Django 5.2.5 on 2025-08-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsIndustrySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('score', models.FloatField(default=0.0)),
                ('details_json', models.JSONField(default=list)),
                ('top_news_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='reference.industry')),
            ],
            options={
                'indexes': [models.Index(fields=['industry', 'window_end'], name='analytics_a_industr_d1eb39_idx'), models.Index(fields=['window_start', 'window_end'], name='analytics_a_window__79f2f9_idx')],
                'unique_together': {('industry', 'window_start', 'window_end')},
            },
        ),
    ]
