# Generated by Django 5.2.5 on 2025-08-23 20:36

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64)),
                ('dim', models.PositiveIntegerField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
