# Generated by Django 5.2.5 on 2025-08-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('text', models.TextField()),
                ('char_len', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('published_at', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text_location', models.CharField(blank=True, default='', max_length=300)),
                ('word_count', models.IntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='ready', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsEmbedding',
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['published_at'], name='news_newsit_publish_9ada03_idx'),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['lang'], name='news_newsit_lang_24c0d9_idx'),
        ),
        migrations.AddField(
            model_name='newschunk',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='news.newsitem'),
        ),
        migrations.AddIndex(
            model_name='newschunk',
            index=models.Index(fields=['news'], name='news_newsch_news_id_71bd8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newschunk',
            unique_together={('news', 'idx')},
        ),
    ]
