# Generated by Django 5.2.5 on 2025-08-24 21:03

import django.db.models.deletion
import research.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_model_summary', models.TextField(blank=True, default='')),
                ('growth_drivers', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='reference.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overview_under_1000w', models.TextField(blank=True, default='')),
                ('trends', models.TextField(blank=True, default='')),
                ('catalysts', models.TextField(blank=True, default='')),
                ('value_chain_summary', models.TextField(blank=True, default='')),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='reference.industry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyCatalyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('positive', models.BooleanField(default=True)),
                ('timeframe_months', models.IntegerField(blank=True, null=True)),
                ('probability_0_1', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('expected_impact', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('as_of', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalysts', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'positive'], name='research_co_company_9518aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyCompetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor_name', models.CharField(blank=True, default='', max_length=200)),
                ('competitor_ticker', models.CharField(blank=True, default='', max_length=20)),
                ('market_share_pct', research.models.PctField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('market_name', models.CharField(blank=True, default='', max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors_of', to='reference.company')),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_targets', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='research_co_company_40f7d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyCustomerShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('customer_name', models.CharField(max_length=200)),
                ('revenue_pct', research.models.PctField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_estimate', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year'], name='research_co_company_37af61_idx')],
                'unique_together': {('company', 'year', 'customer_name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRelatedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('relation_text', models.TextField()),
                ('relation_type', models.CharField(blank=True, default='', max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_stocks', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='research_co_company_34d5c9_idx')],
                'unique_together': {('company', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRevenueByGeography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=120)),
                ('revenue_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('revenue_pct', research.models.PctField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('source_url', models.URLField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_geos', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year'], name='research_co_company_1d82af_idx')],
                'unique_together': {('company', 'year', 'region')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRevenueByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('product', models.CharField(max_length=160)),
                ('revenue_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('revenue_pct', research.models.PctField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('source_url', models.URLField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_products', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year'], name='research_co_company_f4c226_idx')],
                'unique_together': {('company', 'year', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('horizon', models.CharField(choices=[('short', '0-12m'), ('medium', '12-36m'), ('long', '36m+')], default='short', max_length=10)),
                ('severity_1_5', models.IntegerField(default=3)),
                ('likelihood_1_5', models.IntegerField(default=3)),
                ('source_url', models.URLField(blank=True, default='')),
                ('as_of', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'category'], name='research_co_company_0974eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanySupplierShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=200)),
                ('cost_pct', research.models.PctField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_estimate', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year'], name='research_co_company_e74c9e_idx')],
                'unique_together': {('company', 'year', 'supplier_name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyThesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('for', 'Bull'), ('against', 'Bear')], max_length=8)),
                ('content', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'side'], name='research_co_company_f82bb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndustryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('supplier', 'Supplier'), ('producer', 'Producer'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('platform', 'Platform'), ('other', 'Other')], default='producer', max_length=20)),
                ('summary_under_300w', models.TextField(blank=True, default='')),
                ('largest_customers_json', models.JSONField(default=list, help_text='[{"name":"X","revenue_pct":30}]')),
                ('largest_suppliers_json', models.JSONField(default=list, help_text='[{"name":"Y","cost_pct":20}]')),
                ('revenue_growth_5y_pct', research.models.PctField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('profit_growth_5y_pct', research.models.PctField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('symbol', models.CharField(blank=True, default='', max_length=20)),
                ('market_cap_usd', models.BigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_roles', to='reference.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='reference.industry')),
            ],
            options={
                'indexes': [models.Index(fields=['industry', 'role'], name='research_in_industr_1c1a68_idx')],
            },
        ),
    ]
