# Generated by Django 5.2.5 on 2025-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryplayer',
            name='role',
            field=models.CharField(choices=[('supplier', 'Supplier'), ('producer', 'Producer'), ('distributor', 'Distributor'), ('retailer', 'Retailer'), ('platform', 'Platform'), ('other', 'Other'), ('investor', 'Investor'), ('analyst', 'Analyst'), ('media', 'Media'), ('government', 'Government')], default='producer', max_length=20),
        ),
    ]
