# Generated by Django 5.2.5 on 2025-08-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_analyticscompanysignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrisk',
            name='horizon',
            field=models.CharField(choices=[('short', '0-12m'), ('medium', '12-36m'), ('long', '36m+'), ('ongoing', 'Ongoing')], default='short', max_length=10),
        ),
    ]
