# Generated by Django 5.2.5 on 2025-09-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsindustrysignal',
            name='last_aggregated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsindustrysignal',
            name='window_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsindustrysignal',
            name='window_score',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=12),
        ),
    ]
