# Generated by Django 5.2.5 on 2025-09-01 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_analyticsindustrysignal_last_aggregated_at_and_more'),
        ('reference', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('rs_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rs_p1m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rs_p3m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rs_p6m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rs_method', models.CharField(default='percentile_relret_1/3/6m_wt=0.2/0.3/0.5', max_length=50)),
                ('stage2_pass', models.BooleanField(default=False)),
                ('stage2_reasons', models.JSONField(blank=True, null=True)),
                ('news_window_score', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('news_weight_factor', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('final_score', models.DecimalField(db_index=True, decimal_places=3, max_digits=7)),
                ('rank', models.IntegerField(db_index=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.company')),
            ],
            options={
                'indexes': [models.Index(fields=['as_of_date', 'final_score'], name='analytics_a_as_of_d_a6d649_idx'), models.Index(fields=['as_of_date', 'rank'], name='analytics_a_as_of_d_1f6b1d_idx')],
                'unique_together': {('company', 'as_of_date')},
            },
        ),
    ]
