# Generated by Django 5.2.5 on 2025-08-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('processed', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='VectorProbe',
        ),
        migrations.AddIndex(
            model_name='jobrun',
            index=models.Index(fields=['name', 'started_at'], name='ops_jobrun_name_6366de_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrun',
            index=models.Index(fields=['started_at'], name='ops_jobrun_started_900956_idx'),
        ),
    ]
