# Generated by Django 5.2.5 on 2025-08-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newschunk_newsitem_delete_newsembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('start_char', models.IntegerField()),
                ('end_char', models.IntegerField()),
                ('norm', models.CharField(blank=True, default='', max_length=256)),
                ('ticker', models.CharField(blank=True, default='', max_length=24)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.IntegerField()),
                ('score_lexical', models.FloatField(default=0.0)),
                ('score_semantic', models.FloatField(default=0.0)),
                ('score_final', models.FloatField(default=0.0)),
                ('method', models.CharField(default='hybrid', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='news.newsitem')),
            ],
            options={
                'indexes': [models.Index(fields=['news'], name='news_newsen_news_id_38cfff_idx'), models.Index(fields=['target_type', 'target_id'], name='news_newsen_target__66e48d_idx')],
            },
        ),
    ]
