# Generated by Django 5.2.5 on 2025-09-01 06:32

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='news_scores_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='scores_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['news_scores_json'], name='idx_news_scores_json_gin'),
        ),
    ]
